# Generated by Django 5.2.7 on 2025-10-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_orderitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="prd_description",
            field=models.TextField(default="no description"),
            preserve_default=False,
        ),
    ]
