# Generated by Django 5.2.7 on 2025-11-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_orderitem_prd_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="prd_type",
            field=models.CharField(
                choices=[
                    ("Starter", "Starter"),
                    ("Main_course", "Main_course"),
                    ("Beverages", "Beverages"),
                    ("Dessert", "Dessert"),
                ],
                default="food",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
