# Generated by Django 5.2.7 on 2025-11-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_orderitem_prd_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="products",
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_prd_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_prd_image",
            field=models.ImageField(blank=True, null=True, upload_to="cart_prd_img/"),
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_prd_name",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cart",
            name="cart_prd_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="prd_price",
            field=models.IntegerField(default=0),
        ),
    ]
