# Generated by Django 5.2.7 on 2025-11-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_cart_products_cart_cart_prd_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="cart_prd_image",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
