# Generated by Django 5.2.7 on 2025-11-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_orderitem_prd_quantity_usertotal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="prd_quantity",
        ),
        migrations.AddField(
            model_name="cart",
            name="prd_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
